name: 'rollback-lookup'
description: 'Lookup previous successful workflow run in the current GH Action Worfklow'
inputs:
  PA_TOKEN:
    description: 'Personal Access Token'
    required: true 
outputs:
  schema: # id of output
    description: 'The output from your script'
  seed: # id of output
    description: 'The output from your script'    
runs:
  using: 'node12'
  main: 'dist/index.js'